// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import dotenv from 'dotenv';
dotenv.config({
  path: '.env.development'
});
export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seeds/seed.ts'
  },
  datasource: {
    url: process.env['DATABASE_URL']
  }
});
